#
# Copyright (C) 2012-2020 Intel Corporation.
# SPDX-License-Identifier: MIT
#

SINUCA_UTILS := ../src/utils
SINUCA_CXXFLAGS := -I$(SINUCA_PROJECT_ROOT)

# This defines the tool location
TOOL_ROOTS := sinuca3_pintool

##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.

$(OBJDIR)file_handler$(OBJ_SUFFIX): $(SINUCA_UTILS)/file_handler.cpp $(SINUCA_UTILS)/file_handler.hpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $(SINUCA_CXXFLAGS) $<

$(OBJDIR)static_trace_writer$(OBJ_SUFFIX): ./utils/static_trace_writer.cpp ./utils/static_trace_writer.hpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $(SINUCA_CXXFLAGS) $<

$(OBJDIR)dynamic_trace_writer$(OBJ_SUFFIX): ./utils/dynamic_trace_writer.cpp ./utils/dynamic_trace_writer.hpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $(SINUCA_CXXFLAGS) $<

$(OBJDIR)memory_trace_writer$(OBJ_SUFFIX): ./utils/memory_trace_writer.cpp ./utils/memory_trace_writer.hpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $(SINUCA_CXXFLAGS) $<

$(OBJDIR)sinuca3_pintool$(OBJ_SUFFIX): sinuca3_pintool.cpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $(SINUCA_CXXFLAGS) $<

$(OBJDIR)sinuca3_pintool$(PINTOOL_SUFFIX): $(OBJDIR)sinuca3_pintool$(OBJ_SUFFIX) $(OBJDIR)static_trace_writer$(OBJ_SUFFIX) $(OBJDIR)dynamic_trace_writer$(OBJ_SUFFIX) $(OBJDIR)memory_trace_writer$(OBJ_SUFFIX) $(OBJDIR)file_handler$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS) $(SINUCA_CXXFLAGS)
