#
# Copyright (C) 2012-2020 Intel Corporation.
# SPDX-License-Identifier: MIT
#

UTILS := ../src/utils
# This defines the tool location
TOOL_ROOTS := sinuca3_pintool

##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.

$(OBJDIR)file_handler$(OBJ_SUFFIX): $(UTILS)/file_handler.cpp $(UTILS)/file_handler.hpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)static_trace_writer$(OBJ_SUFFIX): ./utils/static_trace_writer.cpp ./utils/static_trace_writer.hpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)dynamic_trace_writer$(OBJ_SUFFIX): ./utils/dynamic_trace_writer.cpp ./utils/dynamic_trace_writer.hpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)memory_trace_writer$(OBJ_SUFFIX): ./utils/memory_trace_writer.cpp ./utils/memory_trace_writer.hpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)sinuca3_pintool$(PINTOOL_SUFFIX): $(OBJDIR)sinuca3_pintool$(OBJ_SUFFIX) $(OBJDIR)static_trace_writer$(OBJ_SUFFIX) $(OBJDIR)dynamic_trace_writer$(OBJ_SUFFIX) $(OBJDIR)memory_trace_writer$(OBJ_SUFFIX) $(OBJDIR)file_handler$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS)
