#ifndef SINUCA3_TRACE_READER_TRACE_READER_HPP_
#define SINUCA3_TRACE_READER_TRACE_READER_HPP_

//
// Copyright (C) 2025  HiPES - Universidade Federal do Paraná
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

/**
 * @file sinuca3_trace_reader.hpp
 * @brief Reads trace generated by sinuca3 pintool
 */

#include "trace_reader.hpp"
#include "x86_reader_file_handler.hpp"

namespace sinuca {
namespace traceReader {
namespace sinuca3TraceReader {

struct ContextInfo {
    unsigned int currentBBL;
    unsigned int currentOpcode;
    bool isInsideBBL;
};

class SinucaTraceReader : public TraceReader {
  private:
    DynamicTraceFile **threadsDynFiles;
    MemoryTraceFile **threadsMemFiles;
    struct ContextInfo *thrInfo;

    int numThreads;

    /** @brief Total number of basic blocks in static file */
    unsigned int binaryTotalBBLs;
    /** @brief Vector to store instructions per basic block */
    unsigned int *binaryBBLsSize;
    /** @brief Array containing all instructions */
    InstructionInfo **binaryDict;
    /** @brief InstructionInfo pool */
    InstructionInfo *pool;

    /** @brief Current number of fetched instructions */
    unsigned long fetchInstructions;

    /**
     * @brief Fill instructions dictionary
     * @details Info per instruction:
     * Address        | Ins. Size   | Base Reg    | Index Reg       |
     * Is predicated  | Is prefetch | Is indirect | Is !std mem op  |
     * Is read        | Has read2   | Is write    | Num. Write Regs |
     * Num. Read Regs | Read Regs   | Write Regs  | Ins. Mnemonic   |
     * Branch Type
     */
    int GenerateBinaryDict(StaticTraceFile *);

  public:
    virtual int OpenTrace(const char *, const char *);
    virtual unsigned long GetTraceSize();
    virtual unsigned long GetNumberOfFetchedInstructions();
    virtual void PrintStatistics();
    virtual FetchResult Fetch(InstructionPacket *, unsigned int);
    void CloseTrace();

    inline ~SinucaTraceReader() { this->CloseTrace(); }
};

}  // namespace sinuca3TraceReader
}  // namespace traceReader
}  // namespace sinuca

#endif  // SINUCA3_TRACE_READER_TRACE_READER_HPP_
