#ifndef SINUCA3_TRACE_READER_HPP
#define SINUCA3_TRACE_READER_HPP

//
// Copyright (C) 2024  HiPES - Universidade Federal do Paraná
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

/**
 * @file sinuca3_trace_reader.hpp
 * @brief Reads trace generated by sinuca3 pintool
 */

#include <cstdio>
#include <cstring>

#include "trace_reader.hpp"

namespace sinuca {
namespace traceReader {
namespace sinuca3TraceReader {

class SinucaTraceReader : public TraceReader {
  private:
    FILE *StaticTraceFile;
    FILE *DynamicTraceFile;
    FILE *MemoryTraceFile;

    bool isInsideBBL;
    unsigned int currentBBL;
    unsigned int currentOpcode;

    /** @brief Total number of basic blocks in static file */
    unsigned int binaryTotalBBLs;
    /** @brief Vector to store instructions per basic block */
    unsigned short *binaryBBLsSize;
    /** @brief Array containing all instructions */
    InstructionPacket **binaryDict;

    /** @brief Current number of fetched instructions */
    unsigned long fetchInstructions;

    int GetTotalBBLs();
    /**
     * @brief Fill instructions dictionary
     * @details Info per instruction:
     * Address        | Ins. Size   | Base Reg    | Index Reg       |
     * Is predicated  | Is prefetch | Is indirect | Is !std mem op  |
     * Is read        | Has read2   | Is write    | Num. Write Regs |
     * Num. Read Regs | Read Regs   | Write Regs  | Ins. Mnemonic   |
     * Branch Type
     */
    int GenerateBinaryDict();

    int TraceNextDynamic(unsigned int *);
    /**
     * @brief Get memory addresses accessed and number of bytes
     * read/written by the current instruction
     * @param package Add to package its memory accesses
     */
    int TraceNextMemory(InstructionPacket *package);
    /**
     * @brief Identify next instruction to fetch considering size of
     * current basic block
     * @param ret Return instruction in pointer to InstructionPacket
     */
    FetchResult TraceFetch(InstructionPacket **ret);

  public:
    virtual int OpenTrace(const char *);
    virtual unsigned long GetTraceSize();
    virtual unsigned long GetNumberOfFetchedInstructions();
    virtual void PrintStatistics();
    virtual FetchResult Fetch(const InstructionPacket **);

    inline ~SinucaTraceReader() {
        fclose(this->StaticTraceFile);
        fclose(this->DynamicTraceFile);
        fclose(this->MemoryTraceFile);
    }
};

}  // namespace sinuca3TraceReader
}  // namespace traceReader
}  // namespace sinuca

#endif  // SINUCA3_TRACE_READER_HPP
