#ifndef SINUCA3_SINUCA_TRACER_TRACE_READER_HPP_
#define SINUCA3_SINUCA_TRACER_TRACE_READER_HPP_

//
// Copyright (C) 2025  HiPES - Universidade Federal do Paraná
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

/**
 * @file trace_reader.hpp
 * @brief Implementation of sinuca trace reader suitable for traces generated by
 * single or multi threaded applications. It implements the interface defined
 * in tracer/trace_reader.hpp file.
 */

#include <vector>

#include <tracer/sinuca/utils/dynamic_trace_reader.hpp>
#include <tracer/sinuca/utils/memory_trace_reader.hpp>
#include <tracer/sinuca/utils/static_trace_reader.hpp>
#include <tracer/trace_reader.hpp>

#include "engine/default_packets.hpp"
#include "utils/circular_buffer.hpp"

struct Mutex {
    unsigned long addr;
    bool isBusy;
    int owner;
    int recCont;  // future use for nested Mutexs
    CircularBuffer* waitingThreadsQueue;

    Mutex() {
        waitingThreadsQueue = new CircularBuffer;
        this->waitingThreadsQueue->Allocate(0, sizeof(int));
        this->isBusy = false;
        this->addr = 0;
    }
    ~Mutex() {
        if (this->waitingThreadsQueue) {
            this->waitingThreadsQueue->Deallocate();
            delete this->waitingThreadsQueue;
        }
    }
    void Reset() { this->isBusy = false; }
};

struct Barrier {
    int thrCont;

    Barrier() { this->ResetBarrier(); }
    void ResetBarrier() { this->thrCont = 0; }
};

struct ThreadData {
    DynamicTraceReader dynFile;
    MemoryTraceReader memFile;
    unsigned long currentBasicBlock; /**<Index of basic block. */
    unsigned long fetchedInst;       /**<Number of instructions fetched */
    int currentInst; /**<Index of instruction inside basic block. */
    int parentThreadId;
    bool isInsideBasicBlock;
    bool isThreadAwake;

    int Allocate(const char* sourceDir, const char* imageName, int tid);

    inline ThreadData()
        : currentBasicBlock(0),
          currentInst(0),
          isInsideBasicBlock(0),
          isThreadAwake(false) {}

    /** @brief Check if the version of trace files is as expected. */
    inline bool CheckVersion(unsigned int version) {
        bool dynamicTraceOkay = (dynFile.GetVersionInt() == version);
        bool memoryTraceOkay = (memFile.GetVersionInt() == version);
        return (!dynamicTraceOkay || !memoryTraceOkay);
    }
    /** @brief Check if the target of trace files is as expected. */
    inline bool CheckTargetArch(unsigned int target) {
        bool dynamicTraceOkay = (dynFile.GetTargetInt() == target);
        bool memoryTraceOkay = (memFile.GetTargetInt() == target);
        return (!dynamicTraceOkay || !memoryTraceOkay);
    }
};

/** @brief Check trace_reader.hpp documentation for details */
class SinucaTraceReader : public TraceReader {
  private:
    StaticTraceReader* staticTrace;
    StaticInstructionInfo** instructionDict;
    StaticInstructionInfo* instructionPool;
    int* basicBlockSizeArr;
    unsigned long totalBasicBlocks;
    int totalStaticInst;
    int totalThreads;
    int traceFilesVersion;
    int traceFilesTargetArch;
    bool fetchFailed;

    ThreadData** threadDataArr;
    Barrier globalBarrier;
    std::vector<Mutex *> mutexVec;
    int numberOfActiveThreads;
    bool reachedAbruptEnd;

    /**
     * @brief Fill instructions dictionary.
     * @details Given a basic block of id X and the instruction of index Y,
     * after the dictionary is created, one can access the StaticInstructionInfo
     * of the corresponding instruction with 'instructionDict[X][Y]'.
     * @return 1 on failure, 0 otherwise.
     */
    int GenerateInstructionDict();
    int FetchBasicBlock(int tid);
    int FetchMemoryData(InstructionPacket* ret, int tid);
    bool HasExecutionEnded();

    inline void ResetInstructionPacket(InstructionPacket* pkt) {
        pkt->dynamicInfo.numReadings = 0;
        pkt->dynamicInfo.numWritings = 0;
        pkt->staticInfo = NULL;
    }
    inline bool IsThreadSleeping(int tid) {
        return (!this->threadDataArr[tid]->isThreadAwake);
    }

  public:
    inline SinucaTraceReader()
        : staticTrace(0),
          instructionDict(0),
          instructionPool(0),
          basicBlockSizeArr(0),
          totalBasicBlocks(0),
          totalThreads(0),
          fetchFailed(0),
          numberOfActiveThreads(1) {}
    virtual inline ~SinucaTraceReader() {
        for (int i = 0; i < this->totalThreads; ++i) {
            if (this->threadDataArr[i]) {
                delete this->threadDataArr[i];
            }
        }
        for (unsigned int i = 0; i < this->mutexVec.size(); i++) {
            if (this->mutexVec[i]) {
                delete this->mutexVec[i];
            }
        }
        delete[] this->instructionDict;
        delete[] this->instructionPool;
        delete[] this->basicBlockSizeArr;
        delete this->staticTrace;
    }

    virtual FetchResult Fetch(InstructionPacket* ret, int tid);
    virtual int OpenTrace(const char* imageName, const char* sourceDir);
    virtual void PrintStatistics();

    virtual unsigned long GetNumberOfFetchedInst(int tid) {
        return this->threadDataArr[tid]->fetchedInst;
    }
    virtual unsigned long GetTotalInstToBeFetched(int tid) {
        return this->threadDataArr[tid]->dynFile.GetTotalExecutedInstructions();
    }

    virtual inline int GetTotalThreads() { return this->totalThreads; }
    virtual inline int GetTotalBasicBlocks() { return this->totalBasicBlocks; }
};

#ifndef NDEBUG
int TestTraceReader();
#endif

#endif  // SINUCA3_SINUCA_TRACER_TRACE_READER_HPP_
