#ifndef SINUCA3_DYNAMIC_TRACE_READER_HPP_
#define SINUCA3_DYNAMIC_TRACE_READER_HPP_

//
// Copyright (C) 2025  HiPES - Universidade Federal do Paraná
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

/**
 * @file sinuca3_trace_reader.hpp
 * @brief Reads trace generated by sinuca3 pintool
 */

#include "../x86_file_handler.hpp"
#include "sinuca3.hpp"

namespace tracer {

class DynamicTraceFile : public TraceFileReader {
  public:
    DynamicTraceFile(const char *folderPath, const char *img, THREADID tid);

    int ReadNextBBl(BBLID *);
};

}

#endif