#ifndef SINUCA3_STATIC_TRACE_READER_HPP_
#define SINUCA3_STATIC_TRACE_READER_HPP_

//
// Copyright (C) 2025  HiPES - Universidade Federal do Paraná
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

/**
 * @file sinuca3_trace_reader.hpp
 * @brief Reads trace generated by sinuca3 pintool
 */

#include "../x86_file_handler.hpp"
#include "sinuca3.hpp"

namespace tracer {

class StaticTraceFile {
  private:
    bool isValid;

    unsigned int totalBBLs;
    unsigned int totalIns;
    unsigned int numThreads;

    char *mmapPtr;
    unsigned long mmapOffset;
    unsigned long mmapSize;
    int fd;

    void *GetData(unsigned long);

    void GetFlagValues(InstructionInfo *, DataINS *);

    void GetBranchFields(StaticInstructionInfo *, DataINS *);

    void GetRegs(StaticInstructionInfo *, DataINS *);

  public:
    StaticTraceFile(const char *folderPath, const char *img);

    void ReadNextPackage(InstructionInfo *);

    unsigned int GetNewBBlSize();

    inline unsigned int GetTotalBBLs() { return this->totalBBLs; }

    inline unsigned int GetTotalIns() { return this->totalIns; }

    inline unsigned int GetNumThreads() { return this->numThreads; }

    inline bool Valid() {return this->isValid;}

    ~StaticTraceFile();
};

}

#endif